name: FastInvTest
version: ${project.version}
author: MrMicky
description: Create fast and easy menu in few lines with only one class.
main: fr.mrmicky.fastinvexample.ExamplePlugin
commands:
  testinv:
    description: Open an example GUI.