name: FastInvExamplePlugin
version: 1.0
author: MrMicky
description: Create fast and easy menu in few lines with only one class
main: fr.mrmicky.fastinv.ExemplePlugin
commands:
  testinv:
    description: Open an exemple GUI